import { errorResponse, getDb, json, requireAccount, safeJson } from "@/lib/server";
import { resolveEvidence } from "@/lib/domain";

type Row = Record<string, unknown>;
function mapCase(row: Row, docs: Row[] = []) { const documents = docs.filter((doc) => doc.case_id === row.id).map((doc) => ({ id: String(doc.id), type: doc.type, fileName: doc.file_name, status: doc.status, confidence: Number(doc.confidence) / 1000, fields: safeJson<Record<string, string>>(String(doc.extracted_json || "{}"), {}), issue: doc.issue || undefined })); return { id: row.id, service: row.service, state: row.state, district: row.district, language: row.language, status: row.status, step: row.step, profile: safeJson(String(row.profile_json || "{}"), {}), plan: row.plan_json ? safeJson(String(row.plan_json), []) : undefined, documents, evidence: resolveEvidence(documents), updatedAt: row.updated_at }; }

export async function GET(request: Request) { try { const accountId = await requireAccount(request); const db = await getDb(); const [casesResult, docsResult] = await Promise.all([db.prepare("SELECT * FROM cases WHERE account_id = ? ORDER BY updated_at DESC").bind(accountId).all<Row>(), db.prepare("SELECT d.* FROM documents d JOIN cases c ON c.id = d.case_id WHERE c.account_id = ? ORDER BY d.created_at").bind(accountId).all<Row>()]); return json({ cases: (casesResult.results || []).map((row) => mapCase(row, docsResult.results || [])) }); } catch (error) { return errorResponse(error); } }

export async function POST(request: Request) { try { const accountId = await requireAccount(request); const body = await request.json() as Record<string, unknown>; const id = String(body.id || ""); if (!/^NEEV-[A-Z0-9]{6,12}$/.test(id)) return Response.json({ error: "Invalid case ID" }, { status: 400 }); const now = Date.now(); await (await getDb()).prepare("INSERT INTO cases (id, account_id, service, state, district, language, status, step, profile_json, plan_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").bind(id, accountId, String(body.service || "Identity reconstruction"), String(body.state || ""), String(body.district || ""), body.language === "hi" ? "hi" : "en", String(body.status || "Interview started"), Number(body.step || 0), JSON.stringify(body.profile || {}), body.plan ? JSON.stringify(body.plan) : null, now, now).run(); return json({ ...body, id, updatedAt: now }, 201); } catch (error) { return errorResponse(error); } }

export async function PATCH(request: Request) { try { const accountId = await requireAccount(request); const body = await request.json() as Record<string, unknown>; const id = String(body.id || ""); const db = await getDb(); const owned = await db.prepare("SELECT id FROM cases WHERE id = ? AND account_id = ?").bind(id, accountId).first(); if (!owned) return Response.json({ error: "Case not found" }, { status: 404 }); const now = Date.now(); await db.prepare("UPDATE cases SET service=?, state=?, district=?, language=?, status=?, step=?, profile_json=?, plan_json=?, updated_at=? WHERE id=? AND account_id=?").bind(String(body.service || "Identity reconstruction"), String(body.state || ""), String(body.district || ""), body.language === "hi" ? "hi" : "en", String(body.status || "In progress"), Number(body.step || 0), JSON.stringify(body.profile || {}), body.plan ? JSON.stringify(body.plan) : null, now, id, accountId).run(); return json({ ...body, updatedAt: now }); } catch (error) { return errorResponse(error); } }
